var searchData=
[
  ['ref',['ref',['../namespacesmaug_1_1ref.html',1,'smaug']]],
  ['sampling',['sampling',['../classsmaug_1_1Network.html#ae3f0e8faf737187eb2e686ff59e6fb85',1,'smaug::Network']]],
  ['scatter',['Scatter',['../classsmaug_1_1TiledTensor.html#ab52c088d855dbb81d8cb6195d1c7a3b9a3845e6de2a76c1ba8f8061c8f8e1a004',1,'smaug::TiledTensor']]],
  ['scheduler',['Scheduler',['../classsmaug_1_1Scheduler.html',1,'smaug']]],
  ['scheduleready',['scheduleReady',['../classsmaug_1_1Scheduler.html#a44d782318c3858716b07a3eb38a654da',1,'smaug::Scheduler']]],
  ['scopedstats',['ScopedStats',['../classsmaug_1_1gem5_1_1ScopedStats.html',1,'smaug::gem5']]],
  ['seluop',['SeluOp',['../classsmaug_1_1SeluOp.html',1,'smaug']]],
  ['seluop_3c_20smvbackend_20_3e',['SeluOp&lt; SmvBackend &gt;',['../classsmaug_1_1SeluOp.html',1,'smaug']]],
  ['setarraymemtypeifsimulating',['setArrayMemTypeIfSimulating',['../namespacesmaug.html#a5741f2a1302381ee8184990c767dabf5',1,'smaug']]],
  ['setconcataxis',['setConcatAxis',['../classsmaug_1_1ConcatOp.html#a7620d007636a9a5aba8dedd41f78c1f4',1,'smaug::ConcatOp']]],
  ['setmultiples',['setMultiples',['../classsmaug_1_1RepeatOp.html#a5790fe4077c52a9b34114e33c1f67606',1,'smaug::RepeatOp::setMultiples(const std::vector&lt; int &gt; &amp;_multiples)'],['../classsmaug_1_1RepeatOp.html#aedfb17c0dfb4633d36c0c0093d95466f',1,'smaug::RepeatOp::setMultiples(const std::initializer_list&lt; int &gt; &amp;_multiples)']]],
  ['setnuminputs',['setNumInputs',['../classsmaug_1_1ConcatOp.html#a1fae3ce1c8daa80610ec4e269dec33c8',1,'smaug::ConcatOp']]],
  ['setnumpendinginputs',['setNumPendingInputs',['../classsmaug_1_1Operator.html#a947a54adbd97d03a36db10fa687845ce',1,'smaug::Operator']]],
  ['setshape',['setShape',['../classsmaug_1_1ReshapeOp.html#a4c391b7328ad5b53cfb7c0d23ac5171b',1,'smaug::ReshapeOp::setShape(const std::vector&lt; int &gt; &amp;_shape, DataLayout _layout)'],['../classsmaug_1_1ReshapeOp.html#a1db779c38951f8fe18c71ee980311c4a',1,'smaug::ReshapeOp::setShape(const std::initializer_list&lt; int &gt; &amp;_shape, DataLayout _layout)']]],
  ['setsplitaxis',['setSplitAxis',['../classsmaug_1_1SplitOp.html#a6cdff189ed85b8a32f1494e293a67605',1,'smaug::SplitOp']]],
  ['setsplits',['setSplits',['../classsmaug_1_1SplitOp.html#acee8e824dab0fe69275e74df3c0eaab1',1,'smaug::SplitOp']]],
  ['settile',['setTile',['../classsmaug_1_1TiledTensor.html#a6bc952389734b33b0fcc974e86ae609b',1,'smaug::TiledTensor']]],
  ['shape',['shape',['../classsmaug_1_1TensorBase.html#ac645b3068e3c70acd0f4c97e3e209acf',1,'smaug::TensorBase']]],
  ['sigmoidop',['SigmoidOp',['../classsmaug_1_1SigmoidOp.html',1,'smaug']]],
  ['sigmoidop_3c_20smvbackend_20_3e',['SigmoidOp&lt; SmvBackend &gt;',['../classsmaug_1_1SigmoidOp.html',1,'smaug']]],
  ['smaug',['smaug',['../namespacesmaug.html',1,'']]],
  ['smaugtest',['SmaugTest',['../classsmaug_1_1SmaugTest.html',1,'smaug']]],
  ['smv',['smv',['../namespacesmaug_1_1smv.html',1,'smaug::smv'],['../namespacesmaug.html#a86f4101aba33c2e665f72756836cf2eaa6ff096a0272b4c83966d9c808023ca07',1,'smaug::Smv()']]],
  ['smvacceleratorpool',['SmvAcceleratorPool',['../classsmaug_1_1SmvAcceleratorPool.html',1,'smaug']]],
  ['smvavgpoolingop',['SmvAvgPoolingOp',['../classsmaug_1_1SmvAvgPoolingOp.html',1,'smaug']]],
  ['smvbackend',['SmvBackend',['../classsmaug_1_1SmvBackend.html',1,'smaug']]],
  ['smvbatchnormop',['SmvBatchNormOp',['../classsmaug_1_1SmvBatchNormOp.html',1,'smaug']]],
  ['smvbatchnormoptest',['SmvBatchNormOpTest',['../classsmaug_1_1SmvBatchNormOpTest.html',1,'smaug']]],
  ['smvconvolutionop',['SmvConvolutionOp',['../classsmaug_1_1SmvConvolutionOp.html',1,'smaug']]],
  ['smvconvolutionoptest',['SmvConvolutionOpTest',['../classsmaug_1_1SmvConvolutionOpTest.html',1,'smaug']]],
  ['smveltwiseaddop',['SmvEltwiseAddOp',['../classsmaug_1_1SmvEltwiseAddOp.html',1,'smaug']]],
  ['smveltwisemulop',['SmvEltwiseMulOp',['../classsmaug_1_1SmvEltwiseMulOp.html',1,'smaug']]],
  ['smveltwiseopstest',['SmvEltwiseOpsTest',['../classsmaug_1_1SmvEltwiseOpsTest.html',1,'smaug']]],
  ['smveluop',['SmvEluOp',['../classsmaug_1_1SmvEluOp.html',1,'smaug']]],
  ['smvgreaterequalop',['SmvGreaterEqualOp',['../classsmaug_1_1SmvGreaterEqualOp.html',1,'smaug']]],
  ['smvgreaterop',['SmvGreaterOp',['../classsmaug_1_1SmvGreaterOp.html',1,'smaug']]],
  ['smvhardtanhop',['SmvHardTanhOp',['../classsmaug_1_1SmvHardTanhOp.html',1,'smaug']]],
  ['smvinnerproductop',['SmvInnerProductOp',['../classsmaug_1_1SmvInnerProductOp.html',1,'smaug']]],
  ['smvinnerproductoptest',['SmvInnerProductOpTest',['../classsmaug_1_1SmvInnerProductOpTest.html',1,'smaug']]],
  ['smvlessequalop',['SmvLessEqualOp',['../classsmaug_1_1SmvLessEqualOp.html',1,'smaug']]],
  ['smvlessop',['SmvLessOp',['../classsmaug_1_1SmvLessOp.html',1,'smaug']]],
  ['smvmaxpoolingop',['SmvMaxPoolingOp',['../classsmaug_1_1SmvMaxPoolingOp.html',1,'smaug']]],
  ['smvpoolingop',['SmvPoolingOp',['../classsmaug_1_1SmvPoolingOp.html',1,'smaug']]],
  ['smvpoolingoptest',['SmvPoolingOpTest',['../classsmaug_1_1SmvPoolingOpTest.html',1,'smaug']]],
  ['smvreluop',['SmvReluOp',['../classsmaug_1_1SmvReluOp.html',1,'smaug']]],
  ['smvseluop',['SmvSeluOp',['../classsmaug_1_1SmvSeluOp.html',1,'smaug']]],
  ['smvsigmoidop',['SmvSigmoidOp',['../classsmaug_1_1SmvSigmoidOp.html',1,'smaug']]],
  ['smvsoftmaxop',['SmvSoftmaxOp',['../classsmaug_1_1SmvSoftmaxOp.html',1,'smaug']]],
  ['smvtanhop',['SmvTanhOp',['../classsmaug_1_1SmvTanhOp.html',1,'smaug']]],
  ['smvunaryoptest',['SmvUnaryOpTest',['../classsmaug_1_1SmvUnaryOpTest.html',1,'smaug']]],
  ['softmaxop',['SoftmaxOp',['../classsmaug_1_1SoftmaxOp.html',1,'smaug']]],
  ['softmaxop_3c_20smvbackend_20_3e',['SoftmaxOp&lt; SmvBackend &gt;',['../classsmaug_1_1SoftmaxOp.html',1,'smaug']]],
  ['splitop',['SplitOp',['../classsmaug_1_1SplitOp.html',1,'smaug']]],
  ['startindex',['startIndex',['../classsmaug_1_1Tensor.html#a903887a8f55636b72e5434678fd151a2',1,'smaug::Tensor']]],
  ['state',['state',['../classsmaug_1_1TensorIndexIterator.html#a7df678138345ea73e3dd1a5bc0738ba7',1,'smaug::TensorIndexIterator']]],
  ['switchop',['SwitchOp',['../classsmaug_1_1SwitchOp.html',1,'smaug']]]
];
